# -*- coding: utf-8 -*-
"""Circle.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V4A0MyMSGm4IYlnnQ6VvHnwkTRbFiQNo
"""

print('Расчет площади цилиндра')
print('____________________')
r=int(input('Введите значение радиуса: '))
print('--------------------')
print('Площадь цилиндра - ',3.14*r**2)