# -*- coding: utf-8 -*-
"""cirkle.py2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aG1sqM32pOykHs17ks3PP9GhQfpkf_FQ
"""

print('Расчет площади и объема цилиндра')
print('____________________')
r=int(input('Введите значение радиуса: '))
h=int(input('Введите значение высоты: '))
print('--------------------')
print('Площадь цилиндра - ',3.14*r**2)
print('Обьем цилиндра - ',h*3.14*r**2)